# Generated by Django 4.1.2 on 2024-01-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Cliente',
        ),
    ]
